project:
  type: website
  output-dir: docs

website: 
  title: "ESS 523c Labs"

format:
  html:
    theme:
      light: pulse
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full
  
editor: visual



